spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: ${DB_PLATFORM}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  time:
    access-exp: ${JWT_ACCESS_EXP}
    refresh-exp: ${JWT_REFRESH_EXP}


coolsms:
  access: ${COOLSMS_ACCESS}
  secret: ${COOLSMS_SECRET}
  phone-number: ${COOLSMS_PHONE_NUMBER}

neis:
  authKey: ${NEIS_AUTH_KEY}
